// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhefhppvexefznjmyjok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoZWZocHB2ZXhlZnpuam15am9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1MzE1NjAsImV4cCI6MjA3NjEwNzU2MH0.K6hKPtsdVWaW1DwSgxEGnV3zx3yaTN3756YPKmkiFu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});